
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://chriskizziar.com"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ""

# Google tracking id

google-tracking-id: "UA-151814765-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Chris Kizziar"
title: "{ Chris Kizziar }"
description: "Website and blog by Chris Kizziar, mixing a little bit of SecOps, InfoSec, DevOps, and life. Opinions expressed are mine."
keywords: "kizziar, consultant, architect, secops, infosec, security, devops, cloud, aws, azure, engineer"
favicon: "/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/chriskizziar-favmono.png"

background-img: "../img/grey-wall.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "SecOps. DevOps. DevSecOps. SecDevOps. Build more, better, and faster."
  - text: "Learn something every day."
  - text: "Secure all the things."
  - text: "Be creative and never be afraid to be weird."
  - text: "Protect your privacy."
  - text: "Blah"


me-img: "/img/chriskizziar.jpg"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/chriskizziar-fav-36_x_36.png"
icon-48p: "/img/web-app/chriskizziar-fav-48_x_48.png"
icon-72p: "/img/web-app/chriskizziar-fav-72_x_72"
icon-96p: "/img/web-app/chriskizziar-fav-96_x_96"
icon-144p: "/img/web-app/chriskizziar-fav-144_x_144"
icon-192p: "/img/web-app/chriskizziar-fav-192_x_192"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "chriskizziar"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/symphonytalent_opt.jpg"
    date: "2014 - 2019"
    description: "Symphony Talent - SecOps Architect & DevOps Engineer"
  - image: "/img/timeline/wgu.png"
    date: "October 2018"
    description: "Western Governors University - BS Information Technology Security"
  - image: "/img/timeline/csi.png"
    date: "2013 - 2014"
    description: "Computer Services, Inc. - Windows Server & SQL Engineer"
  - image: "/img/timeline/dla.png"
    date: "2011 - 2013"
    description: "Defense Logistics Agency - Sr. DBA and Systems Engineer"
  - image: "/img/timeline/forscom.png"
    date: "2008 - 2011"
    description: "US Army Forces Command - Database Administrator (CTR)"
  - image: "/img/timeline/glynncounty.png"
    date: "2006 - 2008"
    description: "Glynn County Board of Commissioners - IT & GIS Specialist"

# First image of the Timeline

timeline-img: "/img/chriskizziar.jpg"

###########
# Contact #
###########

email: "chris@chriskizziar.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Chris Kizziar is a SecOps/DevOps architect, tinkerer, and nerd. He lives in Oklahoma with his amazing family who supports his obsession with tech and accepts his many quirks."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "linkedin"
    url: "https://www.linkedin.com/in/christopherkizziar/"
  - title: "facebook"
    url: "https://facebook.com/ckizziar"
  - title: "twitter"
    url: "https://twitter.com/chriskizziar"
  - title: "github"
    url: "https://github.com/ckizziar"
  - title: "bitcoin"
    url: "https://www.blockchain.com/btc/address/39AAjE1XWYHFRmMFv8X3dQCoYqkuBPDKLb"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: fooyay
keybase-in-social: True
keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
